### ISSUE TITLE
Expand Gitlab links

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/trinity#8]
e.g. if someone types !123, post a link to `https://{GITLAB_REPO_URL}/-/issues/123`.

Would require the room to be configured with a gitlab repository so the `GITLAB_REPO_URL` is preset, so it requires #5 first.

**Comment by ahal** [comment]
Just wanted to give a heads up that I'll be (slowly) working on a [generic version](https://github.com/ahal/trinity/commit/de83e23b425ef78affcfb57b365cc8258c35abbf) of this where admins will be able to configure a vector of regexes and subsitution strings per room.

**Comment by bnjbvr** [comment]
Sweet! When it comes to per-room configurations, you can now take inspiration from the mastodon module which does just that, using the new `sys::resolve-room` API. Let me know if you need any help.

**Comment by ahal** [comment]
@bnjbvr thanks, I did use Mastodon as inspiration and have the admin stuff mostly working.. Though since you're offering I do have an unrelated question stemming from me being a Rust noob.

I was wondering how much of a cost there is to read/writing from the kv store and whether it would be better to keep some runtime state so we don't have to load from the store on every message. But the `Component` trait methods don't have a reference to `self`. Is there some idiomatic way to do this in Rust other than global variables? Or maybe I'm overthinking it and `redb` is so fast that it's not worth worrying about..

**Comment by bnjbvr** [comment]
> I was wondering how much of a cost there is to read/writing from the kv store and whether it would be better to keep some runtime state so we don't have to load from the store on every message.

I expect it to be cheap, unless proven otherwise :grinning: We could add timers to see how long it takes to handle one specific message, in some profiling mode maybe.

> But the Component trait methods don't have a reference to self. Is there some idiomatic way to do this in Rust other than global variables?

Oh right, I could look into having the method take a `&mut self` argument, but I expect this would require global state that we'd hide anyways. Feel free to use an unsafe `static mut` `Option<RefCell<T>>` with `T` being the context data structure; as long as we're using monothreaded wasm (which i intend it to be -- the multithreading can happen on a higher-level), that's fine to read it.

**Comment by ahal** [comment]
Thanks for the pointer to `RefCell`. I think I'll just read state from the store for now until it becomes a problem. Part of the issue is that the `Regex` structs aren't serializable, but maybe I can figure out how to implement that trait.

**Comment by bnjbvr** [comment]
The linkify module allows to implement this quite easily, so closing this one. Thanks @ahal!
